### ISSUE TITLE
Add tests thoroughly

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#2]
To make the grammar more stable, we must add tests for each components (grammar, editor, renderer) more thoroughly and collecting sets of good test examples.

- [ ] Tests for how each channel is encoded for given mark type and field type (#185)
- [ ] Tests for default values of the grammar
- [ ] Tests for arrangements of views and tracks
- [ ] Tests for `<HiGlassComponents/>`
  - https://github.com/higlass/higlass/tree/develop/test
  - https://github.com/higlass/higlass-sequence/tree/master/test
- [ ] Examples in the editor should be tested to more safely deploy (#97)
- [ ] Add tests for circular brush (#111)
