### ISSUE TITLE
Support Sashimi Plot

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#585]
![Screen Shot 2021-11-18 at 10 43 06 AM](https://user-images.githubusercontent.com/9922882/142447959-ca5bb2de-f263-4698-ab9c-559bddfed521.png)

Resources:
- MISO: https://miso.readthedocs.io/en/fastmiso/sashimi.html#why-is-it-called-sashimi-plot
- IGV: http://software.broadinstitute.org/software/igv/Sashimi
- ggsashimi: https://github.com/guigolab/ggsashimi/blob/master/ggsashimi.py
   - https://jbrowse.org/code/jb2/v1.5.1/?session=local-ncGnIgOgs
- Different Representation: https://github.com/jmw86069/splicejam
- https://github.com/isihya/long_read_isoform_visualizer
- Annotation Tool: https://github.com/griffithlab/regtools
- JBrowse: https://github.com/elsiklab/sashimiplot

**Comment by sehilyi** [comment]
The splice junctions can be inferred by using both a **BAM file** and a **BED/GFF file**. 

However, Gosling does not allow combining multiple datasets in a single track. Given that we load BAM data using worker for the performance, we allow users to feed a BED/GFF file to the BAM data fetcher so that the junction annotation can be inferred directly from the BAM worker:

```js
{
   type: 'bam',
   url: '...',
   indexUrl: '...',
   splice: { annotationUrl: '...' } // when specified, we infer junctions with coverage
}
```

**Comment by sehilyi** [comment]
**To-Do**
- [ ] Ignore skipped ranges (`N`) when calculating coverages
- [ ] Coverage calculation directly from the BAM worker
- [ ] A way to flip some of arcs

**Comment by sehilyi** [comment]
As part of a post-1.0 cleanup of Gosling issues, we are closing stale issues that are no longer planned. If this is still relevant, feel free to reopen or start a discussion. Thanks!
